### PR TITLE
add typedefination

### PR DESCRIPTION
**Pull request by taoqf**

### CODE REVIEW

**Comment by taoqf** [comment]
@jakesgordon Could you please take a look at this pr?

**Comment by taoqf** [comment]
@jakesgordon ? are you still work on this? I do need this badly.

**Comment by taoqf** [comment]
@jakesgordon Could you please take a look at this pr?

**Comment by taoqf** [comment]
@jakesgordon

**Comment by taoqf** [comment]
https://github.com/jakesgordon/javascript-state-machine/issues/140

**Comment by taoqf** [comment]
https://github.com/jakesgordon/javascript-state-machine/issues/141

**Comment by taoqf** [comment]
@jakesgordon , I am still waiting.

**Comment by taoqf** [comment]
@jakesgordon

**Comment by taoqf** [comment]
When will this pr be merged? @jakesgordon

**Comment by taoqf** [comment]
@jakesgordon

**Comment by taoqf** [comment]
@jakesgordon

**Comment by taoqf** [comment]
@jakesgordon

**Comment by florianrueegg** [comment]
Why is this PR not merged? What is missing?

**Comment by Spawnrad** [comment]
Need it too . Please merge it ;)
thanks

**Comment by taoqf** [comment]
@jakesgordon

**Comment by adrianhara** [comment]
Can this please be merged guys?

**Comment by Spawnrad** [comment]
Yes please merge it.

**Comment by taoqf** [comment]
Hi, guys, you are welcome to use this https://www.npmjs.com/package/@taoqf/javascript-state-machine
and I will maintain this until this pr is merged. contribution welcomed.

**Comment by demisx** [comment]
Do we not have type definition for v3 of this project yet?

**Comment by beltschatsar** [comment]
@jakesgordon Any plan to merge this ?

**Comment by ciekawy** [comment]
would be awesome to have typings supported!
If not directly in this project why not update `@types/javascript-state-machine` repo which is independent?

**Pull request closed without merging**
